server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: rental
          uri: http://localhost:8081
          predicates:
            - Path=/carRentals/** 
        - id: reservation
          uri: http://localhost:8082
          predicates:
            - Path=/carReservations/** 
        - id: payment
          uri: http://localhost:8083
          predicates:
            #- Path=/payments/**,/paymentCancellations/**
            - Path=/payments/**
        - id: view
          uri: http://localhost:8084
          predicates:
            - Path= /myPages/**,/carInformations/**
        - id: management
          uri: http://localhost:8085
          predicates:
            - Path=/carManagements/**
        - id: comment
          uri: http://localhost:8086
          predicates:
            - Path=/comments/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: rental
          uri: http://rental:8080
          predicates:
            - Path=/carRentals/** 
        - id: reservation
          uri: http://reservation:8080
          predicates:
            - Path=/carReservations/** 
        - id: payment
          uri: http://payment:8080
          predicates:
            #- Path=/payments/**,/paymentCancellations/**
            - Path=/payments/**
        - id: view
          uri: http://view:8080
          predicates:
            - Path= /myPages/**,/carInformations/**
        - id: management
          uri: http://management:8080
          predicates:
            - Path=/carManagements/**
        - id: comment
          uri: http://comment:8080
          predicates:
            - Path=/comments/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
